apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nhlstats-web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nhlstats-web
  minReplicas: {{ .Values.replicas }}
  maxReplicas: {{ mul .Values.replicas 2 }}
  targetCPUUtilizationPercentage: 70
