apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nhlstats-web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nhlstats-web
  minReplicas: {{ .Values.replicas }}
  maxReplicas: {{ mul .Values.replicas 2 }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70