apiVersion: v1
kind: Service
metadata:
  name: nhlstats-web
  namespace: {{ .Values.namespace }}
  labels:
    app: nhlstats-web
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: {{ .Values.nodeport }}
  selector:
    app: nhlstats-web
