apiVersion: v1
kind: Service
metadata:
  name: nhlstats-web
  namespace: nhlstats
  labels:
    app: nhlstats-web
spec:
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  type: LoadBalancer
  selector:
    app: nhlstats-web
