# Generated by Django 3.2.9 on 2022-01-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateField(verbose_name='Game date')),
                ('game_pk', models.IntegerField(default=0, unique=True, verbose_name='Game pk')),
                ('home_team', models.CharField(default='', max_length=100, verbose_name='Home team')),
                ('home_score', models.IntegerField(default=0, verbose_name='Home team score')),
                ('away_team', models.CharField(default='', max_length=100, verbose_name='Away team')),
                ('away_score', models.IntegerField(default=0, verbose_name='Away team score')),
                ('first_toi', models.CharField(default='', max_length=100, verbose_name='Top 1 TOI player')),
                ('first_toi_time', models.IntegerField(default=0, verbose_name='Top 1 TOI player time')),
                ('second_toi', models.CharField(default='', max_length=100, verbose_name='Top 2 TOI player')),
                ('second_toi_time', models.IntegerField(default=0, verbose_name='Top 2 TOI player time')),
                ('third_toi', models.CharField(default='', max_length=100, verbose_name='Top 3 TOI player')),
                ('third_toi_time', models.IntegerField(default=0, verbose_name='Top 3 TOI player time')),
            ],
        ),
    ]
